# Generated by Django 2.2.3 on 2019-07-23 13:00

import datetime
from django.db import migrations, models
import django_resized.forms
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('post_image_full', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to=posts.models.get_image_path)),
                ('post_image_thumb', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[370, 217], upload_to=posts.models.get_image_path)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
