# Generated by Django 2.2.3 on 2019-07-29 09:17

import datetime
from django.db import migrations, models
import django_resized.forms
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_image_full',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to=posts.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_image_thumb',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=0, size=[500, 600], upload_to=posts.models.get_thumbnail_path),
        ),
    ]
