# Generated by Django 2.2.3 on 2019-07-18 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190718_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
