"""
Django settings for NashSat project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.NashSat.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.NashSat.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.NashSat.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1j^*gsd0w8kxy+jj=gd@4!(1h_*2)wz4u%#k7p0)-czq__vjqd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'posts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NashSat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NashSat.wsgi.application'


# Database
# https://docs.NashSat.com/en/2.2/ref/settings/#databases
#
# DATABASES = {
#
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#
# }
DATABASES = {

   'default': {
       'ENGINE': 'django.db.backends.mysql',
       'NAME': 'blog_data',
       'USER': 'ryan',
       'PASSWORD': 'Teamw0rk',
       'HOST': 'localhost',
       'PORT': ''
   }

}


# Password validation
# https://docs.NashSat.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.NashSat.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.NashSat.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = '.Nashsat/posts/template/posts/'
# STATIC_URL = '.Nashsat/posts/template/posts/'
STATIC_ROOT = os.path.join(BASE_DIR, 'posts', 'static')
#STATIC_ROOT = os.path.join(BASE_DIR, 'posts', 'templates', 'posts')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'posts', 'static', 'media')
#
# for r, d, f, in os.walk(STATIC_ROOT):
#     for directories in d:
#         STATICFILES_DIRS.append(os.path.join(r, directories))
#
# for item in STATICFILES_DIRS:
#     print(item)
